# --- GPIO pins ---
HOOK_PIN = 2
DIAL_PULSE_PIN = 3
DIAL_SWITCH_PIN = 4
RINGER_PINS = (17, 27)

# --- Timing (seconds) ---
RING_ON_SECONDS = 2.0
RING_OFF_SECONDS = 3.0
DIAL_COLLECT_TIMEOUT_SECONDS = 3.0
IDLE_SLEEP_SECONDS = 1.0
BT_CHECK_INTERVAL = 10.0

# --- Dial tone ---
DIAL_TONE_FREQUENCY_HZ = 425
